import './globals.css'
import Script from 'next/script'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>

      {/* Font aswesome */}
      <Script
        src='https://kit.fontawesome.com/3fab2f990f.js'
        crossOrigin='anonymous'
        strategy='lazyOnload'
      />
    </html>
  )
}
